v2ex/main/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm 
from flask_pagedown.fields import PageDownField
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, SelectField
from wtforms.validators import Required, Length, Email 
from ..models import Topic, Node 
from v2ex import db 


class TopicForm(FlaskForm):
    """新建话题表单"""
    # nodes_id = [(node.id, node.content) for node in db.session.query(Node).all()]
    title = StringField('标题', validators=[Required(), Length(1, 64)])
    content = PageDownField('内容', validators=[Required()])
    node = SelectField('节点', coerce=int)
    submit = SubmitField('发布')

    def __init__(self, nodes, *args, **kwargs):
        super(TopicForm, self).__init__(*args, **kwargs)
        self.node.choices = [(node.id, node.title) for node in nodes]

    
class PostForm(FlaskForm):
    """新建话题表单"""
    # nodes_id = [(node.id, node.content) for node in db.session.query(Node).all()]
    title = StringField('标题', validators=[Required(), Length(1, 64)])
    content = TextAreaField('内容', validators=[Required()])
    node = SelectField('节点', coerce=int)
    submit = SubmitField('发布')

    def __init__(self, nodes, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.node.choices = [(node.id, node.title) for node in nodes]


class AppendForm(FlaskForm):
    """追加话题内容表单"""
    content = TextAreaField('内容', validators=[Required()])
    submit = SubmitField('追加内容')


class AppendPostForm(FlaskForm):
    """编辑话题表单"""
    content = TextAreaField('内容', validators=[Required()])
    submit = SubmitField('更新')


class CommentForm(FlaskForm):
    """评论表单"""
    content = TextAreaField('评论', validators=[Required()])
    submit = SubmitField('评论')

v2ex/__init__.py
# -*- coding: utf-8 -*-
from flask import Flask 
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_mail import Mail 
from flask_pagedown import PageDown
from flask_msearch import Search
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_moment import Moment
from flask_babelex import Babel 
from config import config 


db = SQLAlchemy()
search1 = Search(db=db)
bootstrap = Bootstrap()
login_manager = LoginManager()
mail = Mail()
pagedown = PageDown()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
admin = Admin(name="后台管理")
moment = Moment()
babel = Babel()


from .models import User, Topic, TopicAppend, Node, Notify, Comment
from .utils import UserView, TopicView, TopicAppendView, CommentView, NodeView, NotifyView


def add_view_to_admin(model_name):
    pass

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    pagedown.init_app(app)
    search1.init_app(app)
    admin.init_app(app)
    moment.init_app(app)
    babel.init_app(app)

    # admin.add_view(AdminModelView(User, db.session, name="管理员"))
    admin.add_view(UserView(User, db.session, name="用户"))
    admin.add_view(TopicView(Topic, db.session, name="话题"))
    admin.add_view(TopicAppendView(TopicAppend, db.session, name="话题追加"))
    admin.add_view(NodeView(Node, db.session, name="节点"))
    admin.add_view(NotifyView(Notify, db.session, name="提醒"))
    admin.add_view(CommentView(Comment, db.session, name="评论"))

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .api import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix="/api/v1.0")
    
    return app 

v2ex/api/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint


api = Blueprint('api', __name__)

from . import views

v2ex/api/views.py
# -*- coding: utf-8 -*-
from flask import jsonify, g, request, current_app, url_for
from flask_restful import Resource, Api, reqparse

from .. import db
from ..models import User, Topic, Node, Notify
from . import api
from .errors import bad_request, internal_server_error, page_not_found
from .authentication import auth

restful_api = Api(api)


class TopicApi(Resource):
    """restful api to get topic
    """

    def __init__(self):
        self.parser = reqparse.RequestParser()
        self.parser.add_argument('title', type=str, required=True,
                                    help='not title provided', location='json')
        self.parser.add_argument('content', type=str, required=True,
                                    help='not content provided', location='json')
        self.parser.add_argument('node_id', type=int, required=True,
                                    help='not node_id provided', location='json')
        super(TopicApi, self).__init__()
    
    def get(self):
        page = int(request.args.get('page', 1, type=int))
        per_page = current_app.config['PER_PAGE']
        offset = (page - 1) * per_page 
        topics = Topic.query.order_by(Topic.create_time.desc()).limit(per_page+offset)
        topics = topics[offset:offset+per_page]
        if not topics:
            return jsonify({"error": "no topics"})
        return jsonify({'topic': [topic.to_json() for topic in topics]})

    @auth.login_required
    def post(self):
        args = self.parser.parse_args()
        topic = Topic(title=args['title'],
                      content=args['content'],
                      node_id=args['node_id'],
                      user=g.current_user)
        db.session.add(topic)
        db.session.commit()
        return jsonify({'status': 200})


class TopicIdApi(Resource):
    """get topic by topic_id
    """
    def get(self, id):
        topic = Topic.query.filter_by(id=id).first()
        if topic is None:
            return jsonify({"error": "no topic"})
        return jsonify(topic.to_json())


restful_api.add_resource(TopicApi, '/topics')
restful_api.add_resource(TopicIdApi, "/topic/<int:id>")

v2ex/main/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from v2ex.utils import format_time

main = Blueprint('main', __name__)
main.add_app_template_filter(format_time, 'format_time')

from . import views 

v2ex/main/views.py
# -*- coding: utf-8 -*-
from flask import request, url_for, redirect, render_template, current_app, flash,\
        abort
from flask_login import login_required, current_user 
from flask_paginate import Pagination
from ..models import db, User, Topic, Node, TopicAppend, Comment
from . import main 
from .. import search1
from .forms import TopicForm, PostForm, AppendForm, AppendPostForm, CommentForm

from ..utils import add_user_links_in_content, add_notify_in_content, get_content_from_redis, \
                    get_v2ex_people_num, get_v2ex_topic_num, get_v2ex_comment_num, \
                    get_v2ex_browse_num, get_top_hot_node, mark_online, get_online_users


# import redis
# r = redis.Redis(host='localhost', port=6379, decode_responses=True)

@main.context_processor
def get_online_count():
    return dict(online_user=get_online_users())


@main.before_request
def mark_current_user_online():
    mark_online(request.remote_addr)


@main.route('/', methods=['GET', 'POST'])
def index():
    per_page = current_app.config['PER_PAGE']
    page = int(request.args.get('page', 1, type=int))
    offset = (page - 1) * per_page 
    topics = Topic.query.order_by(Topic.create_time.desc()).limit(per_page+offset)
    topics = topics[offset:offset+per_page]
    pagination = Pagination(page=page, total=Topic.query.count(),
                        per_page=per_page,
                        record_name='topics',
                        CSS_FRAMEWORK='bootstrap',
                        bs_version=3)
    
    top = get_content_from_redis(key_name="topic", key_type="Topic")
    nodes = get_content_from_redis(key_name="nodes", key_type="Node")

    people_num = get_v2ex_people_num()
    topic_num = get_v2ex_topic_num()
    comment_num = get_v2ex_comment_num()
    browse_num = get_v2ex_browse_num()
    top_nodes = get_top_hot_node()
    online_users = get_online_users()

    return render_template('main/index.html', 
                            pagination=pagination, 
                            topics=topics, nodes=nodes, top=top,
                            people_num=people_num, topic_num=topic_num,
                            browse_num=browse_num, comment_num=comment_num,
                            top_nodes=top_nodes, online=online_users)


@main.route('/topic/hot', methods=['GET', 'POST'])
def hot():
    per_page = current_app.config['PER_PAGE']
    page = int(request.args.get('page', 1, type=int))
    offset = (page-1) * per_page 

    topics = Topic.query.order_by(Topic.reply_num.desc()).limit(per_page+offset)
    topics = topics[offset: offset+per_page]
    pagination = Pagination(page=page, total=Topic.query.count(),
                            per_page=per_page,
                            record_name='topics',
                            CSS_FRAMEWORK='bootstrap',
                            bs_version=3)
    top = get_content_from_redis(key_name="topic", key_type="Topic")
    nodes = get_content_from_redis(key_name="nodes", key_type="Node")
    people_num = get_v2ex_people_num()
    topic_num = get_v2ex_topic_num()
    comment_num = get_v2ex_comment_num()
    browse_num = get_v2ex_browse_num()
    top_nodes = get_top_hot_node()
    online_users = get_online_users()

    return render_template('main/index.html', 
                            pagination=pagination, 
                            topics=topics, nodes=nodes, top=top, 
                            topic_num=topic_num, people_num=people_num, 
                            browse_num=browse_num, comment_num=comment_num,
                            top_nodes=top_nodes, online=online_users)


@main.route('/topic/create', methods=['GET', 'POST'])
@login_required 
def create_topic():
    nodes = Node.query.all()
    form = TopicForm(nodes)
    if form.validate_on_submit():
        topic = Topic(title=form.title.data,
                      content=form.content.data,
                      user=current_user._get_current_object(),
                      node_id=form.node.data)
        db.session.add(topic)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('main/create_topic.html', nodes=nodes, form=form)


@main.route('/topic/new', methods=['GET', 'POST'])
@login_required 
def new_topic():
    nodes = Node.query.all()
    form = PostForm(nodes)
    if form.validate_on_submit():
        topic = Topic(title=form.title.data,
                      content=form.content.data,
                      user=current_user._get_current_object(),
                      node_id=form.node.data)
        db.session.add(topic)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('main/new.html', nodes=nodes, form=form)


@main.route('/topic/<int:tid>', methods=['GET', 'POST'])
def topic_view(tid):
    per_page = current_app.config['PER_PAGE']
    page = int(request.args.get('page', 1, type=int))
    offset = (page - 1) * per_page 

    topic = Topic.query.filter_by(id=tid).first_or_404()
    comments = topic.comments.order_by(Comment.create_time.desc()).limit(per_page+offset)
    # comments = Comment.query.order_by(Comment.create_time.desc()).limit(per_page+offset)
    comments = comments[offset: offset+per_page]
    pagination = Pagination(page=page, total=topic.comments.count(),
                            per_page=per_page,
                            record_name="comments",
                            CSS_FRAMEWORK="bootstrap",
                            bs_version=3)

    form = CommentForm()
    if form.validate_on_submit():
        content = add_user_links_in_content(form.content.data)
        comment = Comment(content=content, 
                          user=current_user._get_current_object(),
                          topic=topic)
        topic.reply_num += 1
        db.session.add(comment)
        db.session.commit()
        add_notify_in_content(form.content.data, current_user.id, tid, comment.id)
        return redirect(url_for('main.topic_view', tid=tid))
    topic.click_num += 1
    db.session.commit()
    return render_template('main/topic.html', topic=topic, pagination=pagination,
                            comments=comments, form=form)


@main.route('/topic/append/<int:tid>', methods=['GET', 'POST'])
@login_required
def topic_append(tid):
    topic = Topic.query.filter_by(id=tid).first_or_404()

    if current_user.id != topic.user.id:
        abort(403)
    form = AppendForm()
    if form.validate_on_submit():
        append = TopicAppend(content=form.content.data,
                             topic_id=tid)
        db.session.add(append)
        db.session.commit()
        return redirect(url_for('main.topic_view', tid=tid))
    return render_template('main/append.html', topic=topic, form=form)
        

@main.route('/topic/edit/<int:tid>', methods=['GET', 'POST'])
@login_required 
def topic_edit(tid):
    topic = Topic.query.filter_by(id=tid).first_or_404()
    nodes = Node.query.all()
    if current_user.id != topic.user.id:
        abort(403)
    
    form = AppendPostForm()
    if form.validate_on_submit():
        topic.content = form.content.data 
        db.session.add(topic)
        db.session.commit()
        return redirect(url_for('main.topic_view', tid=tid))
    form.content.data = topic.content
    return render_template('main/topic_edit.html', topic=topic, form=form)


@main.route('/nodes')
def nodes():
    nodes = Node.query.all()
    return render_template('main/nodes.html', nodes=nodes)


@main.route('/node/<int:nid>')
def node_view(nid):
    node = Node.query.filter_by(id=nid).first_or_404()
    node_title = node.title
    per_page = current_app.config['PER_PAGE']
    page = int(request.args.get('page', 1))
    offset = (page - 1) * per_page

    topics = Topic.query.filter_by(node_id=nid).order_by(
        Topic.create_time.desc()).limit(per_page+offset)
    topics = topics[offset:offset+per_page]
    pagination = Pagination(page=page, 
                        total=Topic.query.filter_by(node_id=nid).count(),
                        per_page=per_page,
                        record_name="comments",
                        CSS_FRAMEWORK="bootstrap",
                        bs_version=3)
    return render_template('main/node_view.html', 
                            topics=topics,
                            node_title=node_title,
                            pagination=pagination, node=node)


@main.route('/search/<keywords>')
def search(keywords):
    results = search1.whoosh_search(Topic, query=keywords, fields=["title"], limit=20)
    results = Topic.query.msearch(keywords, fields=["title"], limit=20)

    per_page = current_app.config["PER_PAGE"]
    page = int(request.args.get("page", 1))
    offset = (page-1) * per_page
    topics = results[offset:offset+per_page]
    pagination = Pagination(page=page, 
                    total=results.count(),
                    per_page=per_page,
                    record_name="comments",
                    CSS_FRAMEWORK="bootstrap",
                    bs_version=3)
    return render_template("main/index.html", topics=topics, pagination=pagination)


@main.route('/topic/test', methods=['GET', 'POST'])
def test():
    return render_template('main/test.html')

v2ex/templates/main/append.html
{% extends 'base_sidebar.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block right %}
{% include 'auth/panel.html' %}
{% endblock %}


{% block left %}

<div class="panel panel-default">
	<div class="topic-heading panel-heading">
		<div class="row">
			<a href="{{ url_for('main.index')}}" class="col-md-1 pull-right">
                <img title="{{ current_user.username}}" class="avatar-large pull-right" src="{{topic.user.avatar_url }}"></a>
			<div class="col-md-10">
				<p class="topic-breadcrumb">
                        <a href="{{ url_for('main.index') }}">Python </a>  ›   <a href="{{ url_for('main.index') }}">{{ topic.node.title }}</a>
                </p>
				<h3 class="list-post-title-in-topic"><a href="{{ url_for('main.topic_view', tid=topic.id)}}" style="color:inherit">{{ topic.title }}</a></h3>
				<p class="list-meta">
					<span class="label label-default list-meta-node"><a href="{{ url_for('main.topic_view', tid=topic.id) }}">{{ topic.node.title }}</a></span>
					<span class="list-count">{{ topic.click_num }}</span>
					<span class="list-time">{{ topic.create_time | format_time }}</span>
					<span class="list-username"><a href="{{ url_for('main.topic_view', tid=topic.id) }}">{{topic.user.username}}</a></span>
					{% if current_user.id == topic.user_id %}
					<a class="label-success label" href="{{ url_for('main.topic_append', tid = topic.id) }}">追加内容</a>
					<a class="label-warning label" href="#">编辑</a>
					{% endif %}
				</p>
			</div>
		</div>
	</div>
	<div class="panel-body">
		{{ topic.content_html | safe}}
	</div>

	<div class="list-group-item list-appendix-item panel-body">
            {{ form.csrf_token }}
            {{ wtf.quick_form(form) }}
		<div class="previewer">
		</div>
	</div>

	{% if topic.appends %}
	<ul class="list-group">
		{% for a in topic.extract_appends() %}
		<div class="list-group-item list-appendix-item">
			<p class="appendix-meta">
				第{{ loop.index }} 追加 {{ a.create_time | format_time }}
			</p>
			{{a.content_html | safe}}
		</div>
		{% endfor %}
	</ul>
	{% endif %}
</div>

{% endblock %}

v2ex/templates/main/create_topic.html
{% extends 'base_sidebar.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
创建话题
{% endblock %}

{% block right %}
{% include 'auth/panel.html' %}
{% endblock %}

{% block left %}
<div class="panel panel-default">
    <div class="panel-heading title-breadcrumb">
        <a href="{{ url_for('main.index') }}">首页</a>
        <span>新话题</span>
    </div>

    <div class="panel-body">

        {% if nodes %}
        <form class="panel-body" method="post" action="">
            <div class="col-md-4">
                    {{ form.csrf_token }}
                    {{ wtf.quick_form(form) }}
            </div>
        </form>>
        {% else %}
        <div class="alert alert-info">
           没有节点可以选择，请管理员添加节点
        </div>
        {% endif %}
        {{ pagedown.include_pagedown() }}
    </div>
</div>
{% endblock %}

v2ex/templates/main/index.html
{% extends 'base_sidebar.html' %}


{% block title %}首页{% endblock %}

{% block header_ext%}
<meta name="keywords" content="hello, world" />
<meta name="description" content="guoweikuang" />
{% endblock %}

{% block right %}
{% include 'auth/panel.html' %}
{% endblock %}
{% block left %}
{% include 'main/list.html' %}
{% endblock %}

v2ex/templates/main/list.html
<div class="panel panel-default">
    <div class="panel-heading title-breadcrumb">
        <ul class="nav nav-pills">
        {% for nid, title in nodes %}
            {% if title == "技术" %}
            <li role="presentation" class="active"><a href="{{ url_for('main.node_view', nid=nid) }}">{{ title }}</a>
            </li>
            {% else %}
            <li role="presentation"><a href="{{ url_for('main.node_view', nid=nid) }}">{{ title }}</a>
            </li>
            {% endif %}

        {% endfor %}
        </ul>    

        {% if username %}
        {{ username }} 的话题
        {% endif %}

        {% if node_title %}
            当前节点为 {{ node_title }}，该节点下总共有 {{ node.topics.count() }} 个话题.
        {% endif %}
    </div>
    

    {% if not topics %}
    <div class="panel-body">
		<div class="alert alert-info">
			没有新话题，去添加吧！！
		</div>
    </div>
    {% else %}
    <ul class="list-group">
        {% for t in topics %}
            <div class="list-group-item list-topic-item" id="{{ t.id }}">
                <div class="row">
                    <a href="{{ url_for('auth.info', uid = t.user_id) }}" class="col-md-1 col-xs-2 col-sm-2">
                        <img title="{{t.user.username}}" class="avatar-middle" src="{{ t.user.avatar_url }}"></a>
                
                    <div class="col-xs-9 col-md-10 col-sm-9">
                        <h3 class="list-post-title"><a href="{{ url_for('main.topic_view', tid=t.id) }}">{{t.title}}</a></h3>
                        <p class="list-meta">
                            <span class="label label-default list-meta-node"><a href="{{ url_for('main.topic_view', tid=t.id) }}">{{ t.node.title }}</a></span>
                            <span class="list-count"> {{t.click_num }} 点击数</span>
                            <span class="list-time">{{ moment(t.create_time, local=True).fromNow(refresh=True) }}</span>
                            <span class="list-username"><a href="{{ url_for('auth.info', uid=t.user_id) }}">{{ t.user.username }}</a></span>
                            <span class="list-reply-count-xs visible-xs">{{ t.reply_num }}</span>
                        </p>
                    </div>
                    <div class="col-xs-1 col-sm-1">
						<span class="badge pull-right list-reply-count hidden-xs">{{t.reply_num }}</span>
					</div>
                </div>


            </div>
        {% endfor %}

    <div class="panel-footer">
        {{ pagination.links }}
	</div>
    {% endif %}
    </ul>
</div>

v2ex/templates/main/node_view.html
{% extends 'base_sidebar.html' %}
{% block right %}
{% include 'auth/panel.html' %}
{% endblock %}
{% block left %}
{% include 'main/list.html' %}
{% endblock %}

v2ex/templates/main/nodes.html
{% extends 'base_sidebar.html' %}
{% block right %}
{% include 'auth/panel.html' %}
{% endblock %}

{% block left %}
  {% if nodes %}
  {% for i in range(0, nodes|length, 4) %}
    <div class="row">
      {% for n in nodes[i: i+4] %}
      <div class="col-md-3">
      <a class="thumbnail" href="{{ url_for ('main.node_view', nid = n.id) }}">
          <span class="badge pull-right"> {{ n.topics.count() }} </span>
      <div class="caption">
        <p class="text-center"><strong>{{ n.title }}</strong></p>
        <p>{{ n.description }}</p>
      </div>
      </a>
      </div>
      {% endfor %}
    </div>
  {% endfor %}

  {% else %}
		<div class="alert alert-danger">
			对不起，我们不能找到任何的节点
		</div>
  {% endif %}

{% endblock %}

v2ex/templates/main/topic.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends 'base_sidebar.html' %}
{% block right %}
{% include 'auth/panel.html' %}
{% endblock %}
{% block left %}
<div class="panel panel-default">
    <div class="topic-heading panel-heading">
        <div class="row">
            <a href="{{ url_for('auth.info', uid=topic.user_id) }}" class="col-md-1 pull-right">
                <img title="{{ current_user.username}}" class="avatar-large pull-right" src="{{ topic.user.avatar_url }}"></a>
                
            <div class="col-md-10">
                    <p class="topic-breadcrumb">
                        <a href="{{ url_for('main.index') }}">首页</a>  ›   <a href="{{ url_for('main.index') }}">{{ topic.node.title }}</a>
                    </p>
                    <h3 class="list-post-title-in-topic">
                        <a href="{{ url_for('main.topic_view', tid=topic.id)}}" style="color:inherit">{{ topic.title }}</a>
                    </h3>
        
                    <p class="list-meta">
                        <span class="label label-default list-meta-node"><a href="{{ url_for('main.topic_view', tid=topic.id) }}">{{ topic.node.title }}</a></span>
                        <span class="list-count">{{ topic.click_num }}</span>
                        <span class="list-time">{{ topic.create_time | format_time}}</span>
                        <span class="list-username"><a href="{{ url_for('auth.info', uid=topic.user_id) }}">{{topic.user.username}}</a></span>
                        {% if current_user.id == topic.user_id %}
                        <a class="label-success label" href="{{ url_for('main.topic_append', tid=topic.id) }}">追加内容</a>
                        <a class="label-warning label" href="{{ url_for('main.topic_edit', tid=topic.id) }}">编辑</a>
                        {% endif %}
                    </p>
                </div>
        </div>
    </div>
    <div class="panel-body">
            {{ topic.content_html | safe}}
        </div>

    {% if topic.appends %}
        <ul class="list-group" id="append">
            {% for a in topic.extract_appends() %}
            {% if not a.deleted %}
            <div class="list-group-item list-appendix-item">
                <p class="appendix-meta">
                    第 {{ loop.index }} 追加 {{ a.create_time | format_time }}
                </p>
                {{a.content_html | safe}}
            </div>
            {% endif %}
            {% endfor %}
        </ul>
    {% endif %}
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <p class="panel-title">
            {% if topic.reply_num %}
            {{ topic.reply_num }} 条评论
            {% else %}
            目前没有评论
            {% endif %}
        </p>
    </div>
    
    {% if topic.reply_num %}
    <ul class="list-group">
        {% for c in comments %}
            <div class="list-group-item list-topic-item" id="comment-{{c.id}}">
                <div class="row">
                    <a href="#" class="col-md-1"><img title="{{ c.user.username}}" class="avatar-middle" src=" {{ c.user.avatar_url }} "></a>
                    <div class="col-xs-11">
                        <div class="row">
                            <div class="reply-author col-sm-10">
                                <a href="#">{{ c.user.username }}</a>
                                <span class="list-time">{{c.create_time | format_time}}</span>

                            </div>
                            <div class="col-sm-2">
                                {% if current_user.is_authenticated %}
                                <a href="#create_reply" data-user="{{c.user.username}}" class="label-info label pull-right reply-btn">回复</a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="reply-content col-md-11" style="margin-top:0.8em">
                                {{c.content_html | safe}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </ul>
    <div class="panel-footer">
        {{ pagination.links}}
    </div>
    {% else %}
	<div class="panel-body">
		<div class="alert alert-info">
			没有评论
		</div>
	</div>
    {% endif %}
    
</div>

<div class="panel panel-default" id="create_reply">
    <div class="panel-heading">
		<p class="panel-title">
			评论
		</p>
    </div> 
    <div class="panel-body">
        {{ form.csrf_token }}
        {{ wtf.quick_form(form) }}
    </div>
</div>
<script src="{{ url_for('static', filename='js/previewer.js') }}"></script>
<script src="{{ url_for('static', filename='js/mention.js') }}"></script>
{% endblock %}

v2ex/templates/main/topic_edit.html
{% extends 'base_sidebar.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block right %}
{% include 'auth/panel.html' %}
{% endblock %}


{% block left %}

<div class="panel panel-default">
	<div class="topic-heading panel-heading">
		<div class="row">
			<a href="{{ url_for('main.index')}}" class="col-md-1 pull-right">
                <img title="{{ current_user.username}}" class="avatar-large pull-right" src="{{topic.user.avatar_url }}"></a>
			<div class="col-md-10">
				<p class="topic-breadcrumb">
                        <a href="{{ url_for('main.index') }}">Python </a>  ›   <a href="{{ url_for('main.index') }}">{{ topic.node.title }}</a>
                </p>
				<h3 class="list-post-title-in-topic"><a href="{{ url_for('main.topic_view', tid=topic.id)}}" style="color:inherit">{{ topic.title }}</a></h3>
				<p class="list-meta">
					<span class="label label-default list-meta-node"><a href="{{ url_for('main.topic_view', tid=topic.id) }}">{{ topic.node.title }}</a></span>
					<span class="list-count">{{ topic.click_num }}</span>
					<span class="list-time">{{ topic.create_time | format_time }}</span>
					<span class="list-username"><a href="{{ url_for('main.topic_view', tid=topic.id) }}">{{topic.user.username}}</a></span>
					{% if current_user.id == topic.user_id %}
					<a class="label-success label" href="{{ url_for('main.topic_append', tid = topic.id) }}">追加内容</a>
					<a class="label-warning label" href="{{ url_for('main.topic_edit', tid=topic.id) }}">编辑</a>
					{% endif %}
				</p>
			</div>
		</div>
	</div>

	<div class="list-group-item list-appendix-item panel-body">
            {{ form.csrf_token }}
            {{ wtf.quick_form(form) }}
		<div class="previewer">
		</div>
	</div>

	{% if topic.appends %}
	<ul class="list-group">
		{% for a in topic.extract_appends() %}
		<div class="list-group-item list-appendix-item">
			<p class="appendix-meta">
				第{{ loop.index }} 追加 {{ a.create_time | format_time }}
			</p>
			{{a.content_html | safe}}
		</div>
		{% endfor %}
	</ul>
	{% endif %}
</div>

{% endblock %}